export enum TodoActionType {
    TODOS_LOAD_START = 'TODOS_LOAD_START',
    TODOS_LOAD_SUCCESS = 'TODOS_LOAD_SUCCESS',
    TODOS_LOAD_ERROR = 'TODOS_LOAD_ERROR',
    ADD_TODO =  'ADD_TODO',
    UPDATE_TODO ='UPDATE_TODO',
    DELETE_TODO = 'DELETE_TODO',
    TOGGLE_COMPLETED = 'TOGGLE_COMPLETED'
};